pipeline {
    agent {
      label 'docker-agent'
    }
    stages {
        stage('Build') {
            steps {
                script {
                    if (env.BRANCH_NAME == 'main') {
                        echo 'Running build on main branch'
                    } else if (env.BRANCH_NAME.contains('feature')) {
                        echo 'Running build on feature branch'
                    } else if (env.BRANCH_NAME.contains('test')) {
                        echo 'Running build on test branch'
                    }
                      else {
                        error('Branch not allowed to run this pipeline')
                    }
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    if (env.BRANCH_NAME == 'main' || env.BRANCH_NAME.contains('feature') || env.BRANCH_NAME.contains('test')) {
                        echo 'Running tests'
                        // Add your test steps here
                    } else {
                        error('Branch not allowed to run this pipeline')
                    }
                }
            }
        }
        stage('CodeCoverage') {
            steps {
                script {
                    if (env.BRANCH_NAME == 'main') {
                        echo 'Running code coverage on main branch'
                        // Add your code coverage steps here
                    } else {
                        echo 'Skipping code coverage'
                    }
                }
            }
        }
    }
    post {
      success {
        echo 'pipeline ran perfectly'
        } 
      failure {
        echo 'pipeline failure'
        }
    }
}
